// flow-typed signature: 3cae751fa9192bdbfa75af3a58e41306
// flow-typed version: <<STUB>>/@fizker/fix-lockfile_v^1.1.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fizker/fix-lockfile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fizker/fix-lockfile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fizker/fix-lockfile/cli' {
  declare module.exports: any;
}

declare module '@fizker/fix-lockfile/dist/diff-packages' {
  declare module.exports: any;
}

declare module '@fizker/fix-lockfile/dist/exec' {
  declare module.exports: any;
}

declare module '@fizker/fix-lockfile/dist/git' {
  declare module.exports: any;
}

declare module '@fizker/fix-lockfile/dist/read-files' {
  declare module.exports: any;
}

declare module '@fizker/fix-lockfile/dist/restore-lockfile' {
  declare module.exports: any;
}

declare module '@fizker/fix-lockfile/dist/run' {
  declare module.exports: any;
}

declare module '@fizker/fix-lockfile/dist/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fizker/fix-lockfile/cli.js' {
  declare module.exports: $Exports<'@fizker/fix-lockfile/cli'>;
}
declare module '@fizker/fix-lockfile/dist/diff-packages.js' {
  declare module.exports: $Exports<'@fizker/fix-lockfile/dist/diff-packages'>;
}
declare module '@fizker/fix-lockfile/dist/exec.js' {
  declare module.exports: $Exports<'@fizker/fix-lockfile/dist/exec'>;
}
declare module '@fizker/fix-lockfile/dist/git.js' {
  declare module.exports: $Exports<'@fizker/fix-lockfile/dist/git'>;
}
declare module '@fizker/fix-lockfile/dist/read-files.js' {
  declare module.exports: $Exports<'@fizker/fix-lockfile/dist/read-files'>;
}
declare module '@fizker/fix-lockfile/dist/restore-lockfile.js' {
  declare module.exports: $Exports<'@fizker/fix-lockfile/dist/restore-lockfile'>;
}
declare module '@fizker/fix-lockfile/dist/run.js' {
  declare module.exports: $Exports<'@fizker/fix-lockfile/dist/run'>;
}
declare module '@fizker/fix-lockfile/dist/types.js' {
  declare module.exports: $Exports<'@fizker/fix-lockfile/dist/types'>;
}
declare module '@fizker/fix-lockfile/index' {
  declare module.exports: $Exports<'@fizker/fix-lockfile'>;
}
declare module '@fizker/fix-lockfile/index.js' {
  declare module.exports: $Exports<'@fizker/fix-lockfile'>;
}
