// flow-typed signature: 4f32de2cd7249441342af3f7e211e9e9
// flow-typed version: <<STUB>>/fmerge_v^1.2.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fmerge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fmerge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fmerge/fmerge.min' {
  declare module.exports: any;
}

declare module 'fmerge/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fmerge/fmerge.min.js' {
  declare module.exports: $Exports<'fmerge/fmerge.min'>;
}
declare module 'fmerge/index' {
  declare module.exports: $Exports<'fmerge'>;
}
declare module 'fmerge/index.js' {
  declare module.exports: $Exports<'fmerge'>;
}
declare module 'fmerge/install.js' {
  declare module.exports: $Exports<'fmerge/install'>;
}
